<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students [
    <!ELEMENT students (student+)>
    <!ELEMENT student (name, age, course, grade)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT age (#PCDATA)>
    <!ELEMENT course (#PCDATA)>
    <!ELEMENT grade (#PCDATA)>
]>
<?xml-stylesheet type="text/css" href="style.css"?>
<students>
    <student>
        <name>Aditya Krishnat Savant</name>
        <age>20</age>
        <course>Computer Science</course>
        <grade>A</grade>
    </student>
    <student>
        <name>Krishna Patil</name>
        <age>21</age>
        <course>Information Technology</course>
        <grade>B</grade>
    </student>
    <student>
        <name>Rohan Desai</name>
        <age>22</age>
        <course>Mechanical Engineering</course>
        <grade>B+</grade>
    </student>
    <student>
        <name>Sneha Kulkarni</name>
        <age>20</age>
        <course>Electronics and Communication</course>
        <grade>A+</grade>
    </student>
    <student>
        <name>Pooja Sharma</name>
        <age>19</age>
        <course>Civil Engineering</course>
        <grade>A</grade>
    </student>
</students>
